<?php

namespace App\Models\Sosmed;

use Illuminate\Database\Eloquent\Model;

class Crowdtangle extends Model
{
    protected $table="crowdtangle_facebook";

    protected $fillable = [
        'tanggal',
        'page_name',
        'user_name',
        'page_id',
        'url',
        'beginning_of_interval',
        'complete',
        'page_likes',
        'page_like_growth',
        'post_count',
        'total_interactions',
        'interaction_growth',
        'interaction_rate',
        'comments',
        'shares',
        'total_reactions_including_likes',
        'likes',
        'angry',
        'haha',
        'wow',
        'sad',
        'love',
        'photo_posts',
        'photo_interactions',
        'photo_interaction_rate',
        'link_posts',
        'link_interactions',
        'link_interaction_rate',
        'status_posts',
        'status_interactions',
        'status_interaction_rate',
        'facebook_video_posts_excluding_live',
        'facebook_video_interactions_excluding_live',
        'facebook_video_interaction_rate_excluding_live',
        'facebook_live_video_posts',
        'facebook_live_interactions',
        'facebook_live_interaction_rate',
        'owned_facebook_video_posts_fb_video_and_live',
        'owned_video_views_fb_video_and_live',
        'owned_video_views_from_page_posts_fb_video_and_live',
        'owned_video_views_fb_video',
        'owned_video_views_fb_live',
        'owned_video_views_from_shares_fb_video_and_live',
        'videos_shared_by_page_not_included_in_owned_videos',
        'video_views_on_videos_shared_by_page',
        'total_video_time',
        'videos_unknown_owned_video_views',
        'videos_unknown_owned_facebook_videos',
        'videos_unknown_videos_shared_by_page_niov',
        'videos_unknown_video_views_on_videos_shared_by_page',
        'videos_0_15_seconds_owned_video_views',
        'videos_0_15_seconds_owned_video_views_from_page_posts',
        'videos_0_15_seconds_owned_facebook_videos',
        'videos_0_15_seconds_videos_shared_by_page_niov',
        'videos_0_15_seconds_video_views_on_videos_shared_by_page',
        'videos_15_30_seconds_owned_video_views',
        'videos_15_30_seconds_owned_video_views_from_page_posts',
        'videos_15_30_seconds_owned_facebook_videos',
        'videos_15_30_seconds_videos_shared_by_page_niov',
        'videos_15_30_seconds_video_views_on_videos_shared_by_page',
        'videos_31_60_seconds_owned_video_views',
        'videos_31_60_seconds_owned_video_views_from_page_posts',
        'videos_31_60_seconds_owned_facebook_videos',
        'videos_31_60_seconds_videos_shared_by_page_niov',
        'videos_31_60_seconds_video_views_on_videos_shared_by_page',
        'videos_1_2_minutes_owned_video_views',
        'videos_1_2_minutes_owned_video_views_from_page_posts',
        'videos_1_2_minutes_owned_facebook_videos',
        'videos_1_2_minutes_videos_shared_by_page_niov',
        'videos_1_2_minutes_video_views_on_videos_shared_by_page',
        'videos_2_3_minutes_owned_video_views',
        'videos_2_3_minutes_owned_video_views_from_page_posts',
        'videos_2_3_minutes_owned_facebook_videos',
        'videos_2_3_minutes_videos_shared_by_page_niov',
        'videos_2_3_minutes_video_views_on_videos_shared_by_page',
        'videos_3_minutes_owned_video_views',
        'videos_3_minutes_owned_video_views_from_page_posts',
        'videos_3_minutes_owned_facebook_videos',
        'videos_3_minutes_videos_shared_by_page_niov',
        'videos_3_minutes_video_views_on_videos_shared_by_page',
    ];
}
