<?php

namespace App\Imports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\ToModel;
use App\Models\Sosmed\Crowdtangle;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithStartRow;

class ImportCrowdtangle implements ToModel, WithStartRow
{
    /**
    * @param Collection $collection
    */
    public function model(array $row)
    {
        return new Crowdtangle([
            'tanggal'=>date('Y-m-d'),
            'page_name'=>$row[0],
            'user_name'=>$row[1],
            'page_id'=>$row[2],
            'url'=>$row[3],
            'beginning_of_interval'=>date('Y-m-d H:i:s',strtotime($row[4])),
            'complete'=>$row[5],
            'page_likes'=>$row[6],
            'page_like_growth'=>$row[7],
            'post_count'=>$row[8],
            'total_interactions'=>$row[9],
            'interaction_growth'=>$row[10],
            'interaction_rate'=>$row[11],
            'comments'=>$row[12],
            'shares'=>$row[13],
            'total_reactions_including_likes'=>$row[14],
            'likes'=>$row[15],
            'angry'=>$row[16],
            'haha'=>$row[17],
            'wow'=>$row[18],
            'sad'=>$row[19],
            'love'=>$row[20],
            'photo_posts'=>$row[21],
            'photo_interactions'=>$row[22],
            'photo_interaction_rate'=>$row[23],
            'link_posts'=>$row[24],
            'link_interactions'=>$row[25],
            'link_interaction_rate'=>$row[26],
            'status_posts'=>$row[27],
            'status_interactions'=>$row[28],
            'status_interaction_rate'=>$row[29],
            'facebook_video_posts_excluding_live'=>$row[30],
            'facebook_video_interactions_excluding_live'=>$row[31],
            'facebook_video_interaction_rate_excluding_live'=>$row[32],
            'facebook_live_video_posts'=>$row[33],
            'facebook_live_interactions'=>$row[34],
            'facebook_live_interaction_rate'=>$row[35],
            'owned_facebook_video_posts_fb_video_and_live'=>$row[36],
            'owned_video_views_fb_video_and_live'=>$row[37],
            'owned_video_views_from_page_posts_fb_video_and_live'=>$row[38],
            'owned_video_views_fb_video'=>$row[39],
            'owned_video_views_fb_live'=>$row[40],
            'owned_video_views_from_shares_fb_video_and_live'=>$row[41],
            'videos_shared_by_page_not_included_in_owned_videos'=>$row[42],
            'video_views_on_videos_shared_by_page'=>$row[43],
            'total_video_time'=>$row[44],
            'videos_unknown_owned_video_views'=>$row[45],
            'videos_unknown_owned_facebook_videos'=>$row[46],
            'videos_unknown_videos_shared_by_page_niov'=>$row[47],
            'videos_unknown_video_views_on_videos_shared_by_page'=>$row[48],
            'videos_0_15_seconds_owned_video_views'=>$row[49],
            'videos_0_15_seconds_owned_video_views_from_page_posts'=>$row[50],
            'videos_0_15_seconds_owned_facebook_videos'=>$row[51],
            'videos_0_15_seconds_videos_shared_by_page_niov'=>$row[52],
            'videos_0_15_seconds_video_views_on_videos_shared_by_page'=>$row[53],
            'videos_15_30_seconds_owned_video_views'=>$row[54],
            'videos_15_30_seconds_owned_video_views_from_page_posts'=>$row[55],
            'videos_15_30_seconds_owned_facebook_videos'=>$row[56],
            'videos_15_30_seconds_videos_shared_by_page_niov'=>$row[57],
            'videos_15_30_seconds_video_views_on_videos_shared_by_page'=>$row[58],
            'videos_31_60_seconds_owned_video_views'=>$row[59],
            'videos_31_60_seconds_owned_video_views_from_page_posts'=>$row[60],
            'videos_31_60_seconds_owned_facebook_videos'=>$row[61],
            'videos_31_60_seconds_videos_shared_by_page_niov'=>$row[62],
            'videos_31_60_seconds_video_views_on_videos_shared_by_page'=>$row[63],
            'videos_1_2_minutes_owned_video_views'=>$row[64],
            'videos_1_2_minutes_owned_video_views_from_page_posts'=>$row[65],
            'videos_1_2_minutes_owned_facebook_videos'=>$row[66],
            'videos_1_2_minutes_videos_shared_by_page_niov'=>$row[67],
            'videos_1_2_minutes_video_views_on_videos_shared_by_page'=>$row[68],
            'videos_2_3_minutes_owned_video_views'=>$row[69],
            'videos_2_3_minutes_owned_video_views_from_page_posts'=>$row[70],
            'videos_2_3_minutes_owned_facebook_videos'=>$row[71],
            'videos_2_3_minutes_videos_shared_by_page_niov'=>$row[72],
            'videos_2_3_minutes_video_views_on_videos_shared_by_page'=>$row[73],
            'videos_3_minutes_owned_video_views'=>$row[74],
            'videos_3_minutes_owned_video_views_from_page_posts'=>$row[75],
            'videos_3_minutes_owned_facebook_videos'=>$row[76],
            'videos_3_minutes_videos_shared_by_page_niov'=>$row[77],
            'videos_3_minutes_video_views_on_videos_shared_by_page'=>$row[78],
            'created_at'=>date('Y-m-d H:i:s'),
            'updated_at'=>date('Y-m-d H:i:s')

            // 'tanggal'=>date('Y-m-d'),
            // 'page_name'=>$row['page_name'],
            // 'user_name'=>$row['user_name'],
            // 'page_id'=>$row['page_id'],
            // 'url'=>$row['url'],
            // 'beginning_of_interval'=>$row['beginning_of_interval'],
            // 'complete'=>$row['complete'],
            // 'page_likes'=>$row['page_likes'],
            // 'page_like_growth'=>$row['page_like_growth'],
            // 'post_count'=>$row['post_count'],
            // 'total_interactions'=>$row['total_interactions'],
            // 'interaction_growth'=>$row['interaction_growth'],
            // 'interaction_rate'=>$row['interaction_rate'],
            // 'comments'=>$row['comments'],
            // 'shares'=>$row['shares'],
            // 'total_reactions_including_likes'=>$row['total_reactions_including_likes'],
            // 'likes'=>$row['likes'],
            // 'angry'=>$row['angry'],
            // 'haha'=>$row['haha'],
            // 'wow'=>$row['wow'],
            // 'sad'=>$row['sad'],
            // 'love'=>$row['love'],
            // 'photo_posts'=>$row['photo_posts'],
            // 'photo_interactions'=>$row['photo_interactions'],
            // 'photo_interaction_rate'=>$row['photo_interaction_rate'],
            // 'link_posts'=>$row['link_posts'],
            // 'link_interactions'=>$row['link_interactions'],
            // 'link_interaction_rate'=>$row['link_interaction_rate'],
            // 'status_posts'=>$row['status_posts'],
            // 'status_interactions'=>$row['status_interactions'],
            // 'status_interaction_rate'=>$row['status_interaction_rate'],
            // 'facebook_video_posts_excluding_live'=>$row['facebook_video_posts_excluding_live'],
            // 'facebook_video_interactions_excluding_live'=>$row['facebook_video_interactions_excluding_live'],
            // 'facebook_video_interaction_rate_excluding_live'=>$row['facebook_video_interaction_rate_excluding_live'],
            // 'facebook_live_video_posts'=>$row['facebook_live_video_posts'],
            // 'facebook_live_interactions'=>$row['facebook_live_interactions'],
            // 'facebook_live_interaction_rate'=>$row['facebook_live_interaction_rate'],
            // 'owned_facebook_video_posts_fb_video_and_live'=>$row['owned_facebook_video_posts_fb_video_and_live'],
            // 'owned_video_views_fb_video_and_live'=>$row['owned_video_views_fb_video_and_live'],
            // 'owned_video_views_from_page_posts_fb_video_and_live'=>$row['owned_video_views_from_page_posts_fb_video_and_live'],
            // 'owned_video_views_fb_video'=>$row['owned_video_views_fb_video'],
            // 'owned_video_views_fb_live'=>$row['owned_video_views_fb_live'],
            // 'owned_video_views_from_shares_fb_video_and_live'=>$row['owned_video_views_from_shares_fb_video_and_live'],
            // 'videos_shared_by_page_not_included_in_owned_videos'=>$row['videos_shared_by_page_not_included_in_owned_videos'],
            // 'video_views_on_videos_shared_by_page'=>$row['video_views_on_videos_shared_by_page'],
            // 'total_video_time'=>$row['total_video_time'],
            // 'videos_unknown_owned_video_views'=>$row['videos_unknown_owned_video_views'],
            // 'videos_unknown_owned_facebook_videos'=>$row['videos_unknown_owned_facebook_videos'],
            // 'videos_unknown_videos_shared_by_page_niov'=>$row['videos_unknown_videos_shared_by_page_niov'],
            // 'videos_unknown_video_views_on_videos_shared_by_page'=>$row['videos_unknown_video_views_on_videos_shared_by_page'],
            // 'videos_0_15_seconds_owned_video_views'=>$row['videos_0_15_seconds_owned_video_views'],
            // 'videos_0_15_seconds_owned_video_views_from_page_posts'=>$row['videos_0_15_seconds_owned_video_views_from_page_posts'],
            // 'videos_0_15_seconds_owned_facebook_videos'=>$row['videos_0_15_seconds_owned_facebook_videos'],
            // 'videos_0_15_seconds_videos_shared_by_page_niov'=>$row['videos_0_15_seconds_videos_shared_by_page_niov'],
            // 'videos_0_15_seconds_video_views_on_videos_shared_by_page'=>$row['videos_0_15_seconds_video_views_on_videos_shared_by_page'],
            // 'videos_15_30_seconds_owned_video_views'=>$row['videos_15_30_seconds_owned_video_views'],
            // 'videos_15_30_seconds_owned_video_views_from_page_posts'=>$row['videos_15_30_seconds_owned_video_views_from_page_posts'],
            // 'videos_15_30_seconds_owned_facebook_videos'=>$row['videos_15_30_seconds_owned_facebook_videos'],
            // 'videos_15_30_seconds_videos_shared_by_page_niov'=>$row['videos_15_30_seconds_videos_shared_by_page_niov'],
            // 'videos_15_30_seconds_video_views_on_videos_shared_by_page'=>$row['videos_15_30_seconds_video_views_on_videos_shared_by_page'],
            // 'videos_31_60_seconds_owned_video_views'=>$row['videos_31_60_seconds_owned_video_views'],
            // 'videos_31_60_seconds_owned_video_views_from_page_posts'=>$row['videos_31_60_seconds_owned_video_views_from_page_posts'],
            // 'videos_31_60_seconds_owned_facebook_videos'=>$row['videos_31_60_seconds_owned_facebook_videos'],
            // 'videos_31_60_seconds_videos_shared_by_page_niov'=>$row['videos_31_60_seconds_videos_shared_by_page_niov'],
            // 'videos_31_60_seconds_video_views_on_videos_shared_by_page'=>$row['videos_31_60_seconds_video_views_on_videos_shared_by_page'],
            // 'videos_1_2_minutes_owned_video_views'=>$row['videos_1_2_minutes_owned_video_views'],
            // 'videos_1_2_minutes_owned_video_views_from_page_posts'=>$row['videos_1_2_minutes_owned_video_views_from_page_posts'],
            // 'videos_1_2_minutes_owned_facebook_videos'=>$row['videos_1_2_minutes_owned_facebook_videos'],
            // 'videos_1_2_minutes_videos_shared_by_page_niov'=>$row['videos_1_2_minutes_videos_shared_by_page_niov'],
            // 'videos_1_2_minutes_video_views_on_videos_shared_by_page'=>$row['videos_1_2_minutes_video_views_on_videos_shared_by_page'],
            // 'videos_2_3_minutes_owned_video_views'=>$row['videos_2_3_minutes_owned_video_views'],
            // 'videos_2_3_minutes_owned_video_views_from_page_posts'=>$row['videos_2_3_minutes_owned_video_views_from_page_posts'],
            // 'videos_2_3_minutes_owned_facebook_videos'=>$row['videos_2_3_minutes_owned_facebook_videos'],
            // 'videos_2_3_minutes_videos_shared_by_page_niov'=>$row['videos_2_3_minutes_videos_shared_by_page_niov'],
            // 'videos_2_3_minutes_video_views_on_videos_shared_by_page'=>$row['videos_2_3_minutes_video_views_on_videos_shared_by_page'],
            // 'videos_3_minutes_owned_video_views'=>$row['videos_3_minutes_owned_video_views'],
            // 'videos_3_minutes_owned_video_views_from_page_posts'=>$row['videos_3_minutes_owned_video_views_from_page_posts'],
            // 'videos_3_minutes_owned_facebook_videos'=>$row['videos_3_minutes_owned_facebook_videos'],
            // 'videos_3_minutes_videos_shared_by_page_niov'=>$row['videos_3_minutes_videos_shared_by_page_niov'],
            // 'videos_3_minutes_video_views_on_videos_shared_by_page'=>$row['videos_3_minutes_video_views_on_videos_shared_by_page'],
            // 'created_at'=>date('Y-m-d H:i:s'),
            // 'updated_at'=>date('Y-m-d H:i:s')

        ]);
    }

    public function startRow(): int
    {
        return 2;
    }
}
